// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4E16dKfPJ1nnzNDjV3sWO3A9ItaUIvU4',
    appId: '1:1008952228130:web:2ed3ce50317e9af8958d7b',
    messagingSenderId: '1008952228130',
    projectId: 'ielts-project-2f836',
    authDomain: 'ielts-project-2f836.firebaseapp.com',
    storageBucket: 'ielts-project-2f836.firebasestorage.app',
    measurementId: 'G-FPZH53WNFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzX---M3JQQwNKPTqxYKUqR34e9T-skA',
    appId: '1:1008952228130:android:15be23e4c7f9fe7a958d7b',
    messagingSenderId: '1008952228130',
    projectId: 'ielts-project-2f836',
    storageBucket: 'ielts-project-2f836.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDunxR5Tc7ZBYvTzpNg_iUd23QO1ylKoJk',
    appId: '1:1008952228130:ios:68003ad60539d157958d7b',
    messagingSenderId: '1008952228130',
    projectId: 'ielts-project-2f836',
    storageBucket: 'ielts-project-2f836.firebasestorage.app',
    iosBundleId: 'com.example.ieltsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDunxR5Tc7ZBYvTzpNg_iUd23QO1ylKoJk',
    appId: '1:1008952228130:ios:68003ad60539d157958d7b',
    messagingSenderId: '1008952228130',
    projectId: 'ielts-project-2f836',
    storageBucket: 'ielts-project-2f836.firebasestorage.app',
    iosBundleId: 'com.example.ieltsProject',
  );
}
